// Change background colour
function bgColorFunction(event) {
	var color = event.value;
	document.getElementsByTagName('body')[0].style.backgroundColor = color;
}


// Change text colour
function textColorFunction(event){
	var color = event.value;
	document.getElementById('details').style.color=color;
}

// display text with onmouseover events


function mouserOver1(){
	document.getElementById("largeImage1").src = "Photos/konesh.jpg";
	document.getElementById("largeImage2").src = "Photos/Pigeon-Island-header.jpg";
	document.getElementById("largeImage3").src = "Photos/Trincomalee_War_Cemetery.jpg";
	document.getElementById("details").innerHTML ="<u><b>Koneswaram Temple</u> - </b>Thirukoneswaram, or the Holy Koneswaram Temple, is a Hindu temple in Thirukonamalai (Trincomalee) on the east coast of Sri Lanka. The temple lies on a high rocky promontory surrounded on three sides by the sea. It bears a history of over three millennia with its records indicating its roots in 1580 BC. This, still beautiful, historical monument is what remains of what once was a sprawling temple city equal to the ancient city of Madurai, India. You can see a lot of shrines and images in there.<br><br><u><b>Pigeon Island</u> - </b>Floating in the great blue 1km offshore, Pigeon Island, with its powdery white sands and glittering coral gardens, tantalises with possibilities. A nesting area for rock pigeons, the island is beautiful enough, with rock pools and paths running through thickets, but it’s the underwater landscape that’s the real star. The reef here is shallow, making snorkelling almost as satisfying as diving, and it’s home to dozens of corals, hundreds of reef fish (including blacktip reef sharks) and turtles.<br><br><u><b>Trincomalee War Cemetery</u> - </b>Trincomalee British War Cemetery is a British military cemetery in Trincomalee, Sri Lanka, for soldiers of the British Empire who were killed or died during World War II. The cemetery also has graves of Dutch, French, Italian and other allied forces.It is one of the six Commonwealth war cemeteries in Sri Lanka, and maintained by Sri Lankan Ministry of Defense on behalf of the Commonwealth War Graves Commission.";
}

function mouserOver2(){
	document.getElementById("largeImage1").src = "Photos/Nine Arch.jpg";
	document.getElementById("largeImage2").src = "Photos/rawanaella.jpg";
	document.getElementById("largeImage3").src = "Photos/ellarock.jpg";
	document.getElementById("details").innerHTML ="<u><b>Nine Arch Bridge</u> - </b>The Nine Arches Bridge is one of the most beautiful landmarks of Sri Lanka and amongst the top places to visit in Ella. There is an interesting story behind this bridge. When the British stopped the construction of this bridge mid-way due to lack of steel during World War 1, the locals constructed it using stone and bricks. The bridge has stood strong without a single piece of steel since then. The setting of the bridge is extremely charming and is amongst the most popular tourist places in Ella. It is located inside a dense forest near a quaint little village with tea plantations surrounding it. Watching the old world trains pass through this bridge is a sight most loved by the tourists.<br><br><u><b>Ravana Falls</u> - </b>Sri Lanka is abundant with the legends of Ramayana. So much so that even the natural landscapes have compelling stories associated with them. The Ravana Falls and the nearby caves are said to be some of the places where the demon god Ravana hid. These legends and the striking landscape of this Ella attraction pulls many travellers to them. The waterfall is around 82 ft. in height and is layered in three tiers. The third tier is approachable after a sharp rock climb and rewards with some amazing views of the dense greens and the rocky landscape.<br><br><u><b>Ella Rock</u> - </b>Ella Rock is one of the most popular hiking destinations in Ella amongst the most interesting places to visit in Ella. A three-hour easy trek will take you further into the luxuriantly dense forested countryside of Ella attractions. During the trek up till the rock, you will see beautiful tea plantations and get a chance to interact with the tea planters. Once atop the rock, you will be rewarded with breathtaking views of the morning sun rising from behind the lush hills. You will get a bird’s eye view of the scenic valleys rolling for miles. Travellers love to spend some quiet time in peace atop the rock in this popular tourist place in Ella.";;
}

function mouserOver3(){
	document.getElementById("largeImage1").src = "Photos/sigiriyaarts.jpg";
	document.getElementById("largeImage2").src = "Photos/lionpaws.jpg";
	document.getElementById("largeImage3").src = "Photos/sigiriya2.jpg";
	document.getElementById("details").innerHTML ="<u><b>Sigiriya</u> - </b>The great rock fortress, Sigiriya was built by the King Kashyapa. King Kashyapa made this great place to protect himself from his brother King Mogallana. The Sigiriya rock is entwined with a tragic event. The heir to the throne had been King Mogallana, but King Kashyapa had taken power by force. King Kashyapa was afraid that his brother would come back again to take back his right to the throne. Therefore, to protect himself, he built this rock fortress. He did not want any invasion to happen by his brother. The Sigiriya rock is decorated with colorful frescos. However, Moggallana was able to defeat Kashyapa, and after that, the rock fortress was destroyed.<br>Sigiriya was discovered later in 1831 by Europeans. A major of the British army, Jonathan Forbes discovered Sigiriya on his way from Polonnaruwa. Many historians and archaeologists started excavating this rock fortress, and it is through the excavations that all the glory of the rock was discovered. One who goes to the top of the rock would see that it is a citadel, with gardens, and parks.<br><br><b>Arts of Sigiriya - </b>The Sigiriya arts are of beautiful women. It is believed that the drawings are the reflections of the beautiful women who lived in King Kashyapa’s palace. The women were drawn to resemble Apsaras. The facial expressions depicted on the woman’s face, the use of color in the paintings attract tourists.<br><br><b>Sigiriya Lion's Paws - </b> Lion’s Paws is situated just before the summit of Sigiriya Rock. As the name suggests, the structure is composed of two gigantic paws, flanking a staircase that leads to the royal palace. The attraction was initially an exquisitely chiselled and enormous structure of the head, chest and paws of a crouching lion with open jaws, guarding the entrance to the 5th-century royal residence of King Kashyapa I. But all that remains today are the paws, a reminder of the significance and opulence of King Kashyapa’s reign.";
}

function mouserOver4(){
	document.getElementById("largeImage1").src = "Photos/thalpe1.jpg";
	document.getElementById("largeImage2").src = "Photos/mirissa1.jpg";
	document.getElementById("largeImage3").src = "Photos/gallefort.jpg";
	document.getElementById("details").innerHTML ="<u><b>The Rock Pools of Thalpe</u> - </b>Sri Lanka is popular for its beautiful beaches, especially the Southern coast. Many of the most prominent include Unwatuna, Beruwala, Hikkaduwa and Mirissa. All these beaches offer various attractions, However, The Rock Pool of Thalpe provides a beautiful seaside stretch which is ideal for adventurous sea bathing and beach parties. Thalpe, itself has a completely different beauty. It is one of the most beautiful beaches in Sri Lanka, and one where you get relative privacy in comparison to other popular beaches in Sri Lanka. The rock pools in Thalpe are cut off from the coral reef. According to the villagers, about 50 years ago the rock pools were cut out of the corals and used to soak husks of coconut to isolate the coir. <br><br><u><b>Coconut Tree Hill</u> - </b>Coconut Tree Hill is presumably the most well-known place in Mirissa. You can watch the infinite sea and Mirissa bay area from the top of this amazing place. It is one of those attractions in Mirissa, which are great for taking pictures of all the tall beautiful palms overlooking the ocean. You can also enjoy a well-deserved coconut at this place to add an extra memorable element to your journey.<br><br><u><b>Galle Fort</u> - </b>The Galle Fort is a historical, archaeological and architectural heritage monument with more than 400 years of history. UNESCO described it as a World Heritage site for its unique exposition of an urban ensemble which illustrates the interaction of European architecture and South Asian traditions from the 16th to the 19th centuries. Today, the Galle Fort is the largest remaining fortress in Asia built by European settlers.";
}

function mouserOver5(){
	document.getElementById("largeImage1").src = "Photos/yala2.jpg";
	document.getElementById("largeImage2").src = "Photos/yala3.jpg";
	document.getElementById("largeImage3").src = "Photos/yala4.jpg";
	document.getElementById("details").innerHTML ="<u><b>Yala National Park</u> - </b>Yala National Park (also known as Ruhuna National Park) is located in the south eastern region of Sri Lanka and extends over two provinces of Hambantota district of southern province and Monaragala district in Uva province. The entrance to the park is at Palatupana, 12km from Kirinda. The distance from Colombo to the entry point of Palatupana is 305 km. The rocky outcrops scattered over the park provides vantage points to enjoy the sprawling areas with Sri Lanka’s dry zone landscape: low scrub and woods. Stillmore, the southern border of the park being the south-eastern coast, the brackish lagoons and dunes enhances the distinctive charm of the Yala National Park.<br><br><b>Wildlife - </b>Of all the National Parks in Sri Lanka, Yala National Park gives the best opportunity to witness Sri Lanka’s broad variety of wildlife: colorful painted stork in troops are seen perched at the shores of lagoon where the crocodiles too have chosen to doze off; lovely fantailed peacocks in their resplendent blues and greens parade about amidst the woods where monkeys hang, leap and chatter; in the bush jungle are the Elephants; crossing the tracks and wandering off into the thorny scrub jungle is the star attraction of the park: the leopard.<br><br><b>Leopards - </b>Yala National Park’s Block 1, on the western side of the park, the only one of all five blocks open to the visitors, has recorded the highest density of leopards among the leopard populations scattered in the wildlife parks of Sri Lanka. These magnificent beasts have now much habituated to the encroachment of their domains by the humans in jeeps. Young males don’t betray any sign of disturbance; they seem confident roaming over the gravel roads tracks as well as the bush jungle during the day: the visitors enjoy to no ends, fine photographic opportunities to capture the magnificent beasts well focused at the close range.<br><br><b>Birdlife - </b>Yala National Park is rich in birdlife and around 130 species have been recorded.Raptors include crested serpent eagle and white bellied sea eagle. Among the water birds attracted to the lagoons are Lesser Flamingo, Pelicon, Spoonbill, painted stork, rare black necked Stork, grey heron, purple heron, night heron and Darter.";
}

function mouserOver6(){
	document.getElementById("largeImage1").src = "Photos/meemure1.jpg";
	document.getElementById("largeImage2").src = "Photos/meemure2.jpg";
	document.getElementById("largeImage3").src = "Photos/meemure3.jpg";
	document.getElementById("details").innerHTML ="<u><b>Meemure</u> - </b>Meemure is an isolated village in the Central Province of Sri Lanka, located 324m above sea level and hidden amongst the mountains. The only way to reach it is from the  ‘Hunnasgiriya’ mountain, which is part of the Knuckles range, approximately 50km from Kandy. It’s a difficult trail of 33km from Hunnasgiriya to Meemure with many tricky spots, though the view along it is excellent. The village itself receives abundant water in the form of waterfalls that have their sources in the evergreen forests of the Knuckles. East of the village lies the pyramid shaped Lakegala mountain; while the west is dominated by the picturesque Knuckles range. The northern boundary of Meemure borders a forest which runs to the ‘Pitawala Pathana’ grassland; and the south is bounded by Heen River. Pack-bulls used to be the solitary method of transport to Meemure until 2004. Herds of cattle carried sacks full of goods and equipment to the village. Due to the fertility and prosperity of the village; the pack-bulls were only used to carry salt, cloths, tobacco and calcium bicarbonate. But with the invasion of modern technology, the trails have been widened to allow three wheelers, jeeps and small trucks.<br><br><b>Life in the village - </b>The village has a population of approximately 400 with about 125 families. The architecture is one of the main identities of Meemure. The villagers build eco-friendly homes using clay and illuk (spear grass) which lasts for over three decades. But the most unique aspect of their buildings are their boundary walls made of quartz. Before cardamom cultivation was banned in 1982 due to the Forest Preservation Act, Meemure villagers earned their bread by harvesting the spice. After this they shifted to chena cultivation, paddy cultivation and pepper cultivation. Nowadays some of the peasants earn their living by taking care of jaggery palms, which produce toddy and treacle. The village has one tiny village shop where the locals buy necessities such as salt and sugar; and no cable telephone or mobile network signal. The village does have CDMA telephone services, though, to some extent. The villagers don’t have direct mail delivery to the village, either; and have to journey to Thapal Junction each day to exchange incoming and outgoing post with the postman.";
}